version: "3.9"
services:
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        volumes: 
            - ./db/mysql/data:/var/lib/mysql
            - ./db/mysql/conf.d:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker
            MYSQL_USER: docker-user
            MYSQL_PASSWORD: docker-pass
            TZ: 'Asia/Tokyo'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${MYSQL_PORT}:3306

    # nginx:
    #     image: nginx:${NGINX_VERSION}
    #     container_name: nginx
    #     ports:
    #         - ${NGINX_PORT}:8000
    #     volumes: 
    #         - ./web/nginx/conf:/etc/nginx/conf.d
    #         - ./web/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    #         - ./static:/static
    #     depends_on: 
    #         - django

    django:
        build:
            context: ./django/
            args:
                - DJANGO_VERSION=${DJANGO_VERSION}
                - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
                - DJANGO_GIT_BRANCH=${DJANGO_APP_GIT_BRANCH}
                - DJANGO_GIT_REPOS=${DJANGO_APP_GIT_REPOS}
        container_name: django
        # command: uwsgi --socket :${DJANGO_PORT} --module project.wsgi
        entrypoint: "/work/entrypoint.sh"
        tty: true
        volumes: 
            - ./django/work:/work
        ports: 
            - ${DJANGO_PORT}:8000
        expose: 
            - ${DJANGO_PORT}
        depends_on: 
            - mysql
